name: rental_admin_app
description: "Rental app admin dashboard"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  flutter_web_plugins:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.4.10
  fl_chart: ^0.66.0


  # State management
  flutter_riverpod: ^3.0.0

  # Image picker
  image_picker: ^1.0.4
  pdf: ^3.10.7
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
